# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Rahul Jain
tagline:             'Personalized diary'
description:         'Rahuls blog that is maintained as a personal diary as a part of EPICS project for review by faculty incharge'
url:                 http://rahuljain.gearsystems.org/
paginate:            5

# About/contact
author:
  name:              Rahul Jain
  url:               https://twitter.com/arbitrarylover
  email:             rahul2308@outlook.com

# Custom vars
version:             1.0.0
github:
  repo:           https://github.com/gearsystems/rahuljain
